stages:
  prepare_data:
    cmd: python scripts/prepare_data.py
    deps:
      - data/enriched_spans.csv
    outs:
      - data/data_with_anomalies.csv
      - data/prepared_data.csv

  train_model:
    cmd: python scripts/train_model.py
    deps:
      - data/prepared_data.csv
    params:
      - model_params.n_estimators
      - model_params.random_state
      - model_params.n_jobs
      - model_params.max_depth
    outs:
      - model/rf_model.pkl

  evaluate_model:
    cmd: python scripts/evaluate_model.py
    deps:
      - model/rf_model.pkl
      - data/prepared_data.csv
    metrics:
      - metrics/classification_report.json
      - metrics/accuracy.json
    plots:
      - metrics/confusion_matrix.json:
          template: confusion
          x: actual
          y: predicted
      - metrics/feature_importances.json:
          template: default
          x: features
          y: importances
          title: 'Feature Importances'
          x_label: 'Features'
          y_label: 'Importance'